### ISSUE TITLE
Replace long-polling with websocket

### ISSUE THREAD

**Issue by majst01** [metal-stack/metal-api#22]
The current implementation uses long-polling for the `wait` call. A machine calls this function and *hangs* until it is allocated by another client. There is a timeout when the server closes the hanging call (to prevent other network timeouts) and the client will instantly call `wait` again.

When such a timeout occurs, the server returns a 504 status code (Gateway Timeout) which itself is ok. But there are problems with this approach:

 - the log is full of 504 errors which are not really errors. 
 - if we later want to monitor the log for 5xx errors, we have to filter.
 - if we later want to monitor the response-durations, we always have very long response times for the `wait` call, so we also have to filter here.

I'd propose an implementation with websockets, where the client calls the `wait` endpoint which is not a rest-function but the endpoint to a websocket which stays open until one of the partners (client or server) closes the connection. If the connection is lost although it wasn't closed we log an error because this is really an error. When a machine is allocated the machine-struct will be transmitted through the websocket to the client. 

The endpoint `wait` should not be implemented with the restful framework, perhaps it should use a complete different rootpath in the URL with a specific handler in the code. In this case we can exclude this call very easily from generating some metrics like `...response_duration` as this makes no sense with websockets.

### Implications

When using websockets we have to deal with reverse proxies in front of the API service. As websockets are implemented with the `Connection` header which itself is a Hop-By-Hop header we have to configure the reverse proxy to forward the websocket to the metal-api.

---

Sounds good and the way to go, i do not know websockets as deep as you do, but is it still possible to do this wait call through metal-core as we do now ? Or do we need to change the way metal-hammer talks to that endpoint in a more general way ?

---

metal-core has to use `httputil.ReverseProxy` to provide an endpoint for metal-hammer and proxy it to metal-api. go1.12 implemented [this feature](https://go-review.googlesource.com/c/go/+/146437/), i don't see any big problems here.

---

**Comment by majst01** [comment]
@kolsa maybe not exact problem description but can be used as the issue for "use grpc for waitforallocation". Please update here accordingly.

**Comment by kolsa** [comment]
The wait-for-allocation feature is now implemented using gRPC. These are the relevant PRs:

https://github.com/metal-stack/metal-roles/pull/5
https://github.com/metal-stack/mini-lab/pull/7
https://github.com/metal-stack/metal-hammer/pull/14
https://github.com/metal-stack/metal-core/pull/14
https://github.com/metal-stack/metal-api/pull/55
https://github.com/metal-stack/metal-go/pull/20
https://github.com/metal-stack/metalctl/pull/9

**Comment by Gerrit91** [comment]
@kolsa As soon as you have everything at a point where you want your changes to be reviewed, can you also write up a small paragraph on how everything you did is intended to work? Because it looks like the wait response does not contain any allocation data any more. Where does the information now come from? Just things like that to make it a little easier for reviewers to understand the new approach. Thanks :)

**Comment by kolsa** [comment]
The waitTable has been removed entirely together with all related functions.  
A new gRPC server is started in metal-api, serving the wait Service defined in pkg/api/v1/wait.proto on port 50051. Traffic is TLS encrypted and a valid client cert is needed.  
An nginx forward-proxy is installed next-to metal-core (leaf), which simply streams gRPC requests between metal-hammer and metal-core. No TLS termination.  
When metal-hammer reaches the wait-for-installation state it now calls metal-api gRPC wait server endpoint via gRPC nginx forward proxy. The response is a gRPC stream that simply states whether the machine is allocated or not. metal-hammer is informed every 5 seconds about the allocation state of the machine and keeps listening on that stream as long as the machine is finally allocated. It then proceeds as normal.  
On the other end, metal-api keeps the response stream open and checks every 5 seconds the machine allocation field within the DB and writes it into the response stream (this keeps metal-hammer logging - could be omitted). As soon as the machine is allocated it responds accordingly (even if it happens in between the 5 second gaps) and closes the stream, which will metal-hammer cause to start the installation.  
If the server stream breaks due to a metal-api downtime for example, metal-hammer continuously tries to reconnect, which will finally succeed as soon as metal-api is back again. metal-hammer immediately falls back into waiting mode after reconnection, since the machine allocation is still nil.  
In contrary, if metal-hammer machine is rebooted during waiting mode, metal-api simply closes the corrupted stream. When metal-hammer starts again, it opens a new stream and again falls back into the waiting mode.  

Note: metal-hammer extracts the gRPC address (host:port) from the commandLine, that is provided by metal-core within the boot response. As soon as metal-hammer starts the waiting mode it first calls the new certs-service endpoint of metal-core to get the needed gRPC CA and client certificates as well as the client key, which are used then for the gRPC connection.

**Comment by kolsa** [comment]
We could change two points here, if we prefer this:

1. metal-api does not write allocation state into the response stream every 5s at all. It only responds as soon as the machine is allocated. This scenario has two impacts:  
Positive: We would not need a stream response, a simple gRPC response is sufficient.  
Probably negative: metal-hammer does not log anything in the meantime. If you connect to the machine console, you see nothing except the keep-alive events. Probably this would be ok at all.  

1. metal-hammer retrieves the gRPC address from the commandLine. It could be fetched from metal-core together with the certificates from the new certs-service endpoint. Probably we then have to rename this endpoint or provide an extra one.

**Comment by Gerrit91** [comment]
Thanks for explaining your ideas! I have a couple of questions.

- When there is no wait table anymore how do you ensure that a machine gets allocated only once when there are multiple replicas of the metal-api running at the same time? In the current implementation the database is being used for "atomic" operations, how does this work here?
- How do you select from the pool of waiting machines? In the current implementation it randomly retrieves a machine from the wait table (by using the rethinkdb `sample` function). This random variation is actually quite important because the Gardener Machine Controller Manager allocates multiple machine at the same time, such that race conditions should be avoided.
- Why is there a need of a forwarding proxy when the metal-hammer can reach out to the metal-api directly? I think we have the metal-core in between the calls because the metal-core for some endpoints enriches requests from the metal-hammer (e.g. in which rack the machine is located for register). But we are only dealing with the wait endpoint... do we need a proxy?
- How does the metal-hammer get the user allocation data (e.g. which OS image should be installed). Before, we returned this in the wait response. Now that this response is empty... where does the metal-hammer get this information from?

**Comment by kolsa** [comment]
4. Forgot to mention this: as soon as the machine is allocated and the stream is closed by the server, metal-hammer simply fetches the machine details and therewith the allocation. This should be fine without any race conditions.

3. metal-hammer cannot speak to metal-api directly due to our network topology. I think we must have a forward proxy here.

2. I still use the sample function, but now queuing the machineTable rather than the waitTaible. Indeed, there was even no need to change the query filter.

1. There should be no difference, since we only switched the waitTable with the machineTable.

**Comment by ulrichSchreiner** [comment]
hi,

sorry to be the bad guy :-)

i just looked at the current implementation. you changed the polling, now you use a map of chan's where the machine-id is the index. but i do not understand how this will work with multiple running instances of `metal-api`. think of the fact, that the wait-call hangs in one pod and the allocation happens in another pod.

**Comment by majst01** [comment]
Already in place with @kolsa implementation of waitforallocation
