### ISSUE TITLE
switch-service contains strange code

### ISSUE THREAD

**Issue by ulrichSchreiner** [metal-stack/metal-api#4]
in the switch-service we have a function `setVrf` which contains this code:
~~~go
for _, c := range s.MachineConnections[mid] {
    c.Nic.Vrf = vrf
    changed = append(changed, c.Nic)
}
~~~
i'm a little confused with the first line in the loop, because imho this only changes the loop-variable and not the connection itself which is contained in the switch. is this the wanted behaviour? or am i wrong here?

**Comment by mwindower** [comment]
We do not persist the VRF-Association in the Machine-Connections because we than would have to update those in case of machine deletion.

This just extracts the NIC information as seen when the connection was registered.

But yes, it's a bit unclear what happens. I would suggest to use a `map[string][true]` to hold the MACs of switch ports that need to be put into the VRF and use that map directly in the second loop over the current `switch.Nics`.

WDYT?
