### ISSUE TITLE
Terraform provider

### ISSUE THREAD

**Issue by genofire** [metal-stack/metal-api#448]
Maybe it would be nice, to configure the metal-maschines per terraform

**Comment by majst01** [comment]
Yes this was asked already some times, but because we provision our metal machines almost always with our https://gardener.cloud integration to create kubernetes clusters, this is not on our top priority.

We have an working ansible integration here: https://github.com/metal-stack/metal-ansible-modules

**Comment by Gerrit91** [comment]
Reason which held me back from doing more integrations was primarily that the metal-api does not implement resource scoping / project tokens (MEP-4). Without scopes these kind of integrations are too powerful and can lead to quite unpleasant scenarios. 🙈
